ansible_user: netaud
ansible_ssh_private_key_file: /etc/ansible/.ssh/private.key
#ansible_ssh_private_key_file: /var/www/.ssh/id_rsa
#ansible_ssh_private_key_file: /home/adminevgvac/.ssh/private.key
ansible_connection: ansible.netcommon.network_cli
ansible_network_os: cisco.ios.ios
ansible_become: yes
ansible_become_method: enable
ansible_host_key_cheking: false
