ansible_user: netaud
ansible_connection: ansible.netcommon.network_cli
#ansible_network_os: nxos
ansible_network_os: cisco.nxos.nxos
ansible_become: no
ansible_become_method: enable
ansible_host_key_cheking: false
