---
- name: Copy ntp.conf config for ntp1 server
  copy:
    src: ntp1.conf
    dest: /etc/ntp.conf
    mode: 0644
    backup: yes
  notify: Restart service ntp
  when: ansible_hostname == 'dcksv-ntp1'

- name: Copy ntp.conf config for ntp2 server
  copy:
    src: ntp2.conf
    dest: /etc/ntp.conf
    mode: 0644
    backup: yes
  notify: Restart service ntp
  when: ansible_hostname == 'dcksv-ntp2'