---
#- block:
- name: Deactivates the default virtualhost
  command: a2dissite 000-default.conf
  notify: Restart service apache2

- name: Deactivates the default ssl virtualhost
  command: a2dissite default-ssl
  notify: Restart service apache2

- name: Activates our virtualhost
  command: a2ensite site.conf
  notify: Restart service apache2