---
# tasks file for install_kaspersky
- name: Check install klnagent
  command: dpkg-query -W klnagent
  register: pkg_klnagent_install
  failed_when: pkg_klnagent_install.rc > 1
  changed_when: pkg_klnagent_install.rc == 1

- name: Check install kesl
  command: dpkg-query -W kesl
  register: pkg_kesl_install
  failed_when: pkg_kesl_install.rc > 1
  changed_when: pkg_kesl_install.rc == 1

- include: install_klnagent.yml
- include: install_kesl.yml