---
# tasks file for install_kaspersky
- name: Check install kesl
  command: dpkg-query -W kesl
  register: pkg_kesl_install
  failed_when: pkg_kesl_install.rc > 1
  changed_when: pkg_kesl_install.rc == 1

- name: Check install klnagent
  command: dpkg-query -W klnagent
  register: pkg_klnagent_install
  failed_when: pkg_klnagent_install.rc > 1
  changed_when: pkg_klnagent_install.rc == 1

- block: ##### Block Klnagent #####
  - name: Copy Klnagent deb files
    copy:
      src: "{{ kaspersky_agent }}"
      dest: "{{ destination_folder }}"

#  - name: Install Klnagent
#    apt:
#      deb: "{{ destination_folder }}/{{ kaspersky_agent }}"

  when: pkg_klnagent_install.rc == 1

- block: ##### Block Kesl #####
  - name: Copy Kesl deb files
    copy:
      src: "{{ kaspersky_agent }}"
      dest: "{{ destination_folder }}"

#  - name: Install Klnagent
#    apt: 
#      deb: "{{ destination_folder }}/{{ kaspersky_kesl }}"

  when: pkg_kesl_install == 1

#  - name: Copy Klnagent deb files
#    copy:
#        src: "{{ kaspersky_kesl }}"
#        dest: "{{ destination_folder }}"

