---
- name: # Repo file
  copy:
    src: astra/sources.list_astra
    dest: /etc/apt/sources.list
    mode: 0644

- name: Copy Resolv
  copy:
    src: resolv.conf
    dest: /etc/resolv.conf
    mode: 644

- name: Add proxy server-repo
  copy:
    src: astra/apt.conf
    dest: /etc/apt/apt.conf
    mode: 0644

- name: Copy SSH config
  copy:
    src: astra/sshd_config
    dest: /etc/ssh/sshd_config
    mode: 0644
  notify: Restart service SSH
  
- name: Copy .bashrc config
  copy:
    src: astra/.bashrc
    dest: /root/.bashrc
    mode: 0644

- name: Copy inputrc config
  copy:
    src: astra/inputrc
    dest: /etc/inputrc
    mode: 0644
  
- name: Copy bash.bashrc config
  copy:
    src: astra/bash.bashrc
    dest: /etc/bash.bashrc
    mode: 0644

- name: Copy inputrc config
  copy:
    src: astra/sysctl.conf
    dest: /etc/sysctl.conf
    mode: 0644

- name: Copy timesyncd.conf config
  copy:
    src: astra/timesyncd.conf
    dest: /etc/systemd/timesyncd.conf
    mode: 0644
  notify: Restart service systemd-timesyncd