---
- name: Add proxy server-repo
  copy:
    src: debian/apt.conf
    dest: /etc/apt/apt.conf
    mode: 0644

- name: Add proxy server-repo
  copy:
    src: debian/sources.list
    dest: /etc/apt/sources.list
    mode: 0644

- name: Copy SSH config
  copy:
    src: debian/sshd_config
    dest: /etc/ssh/sshd_config
    mode: 0644
  
- name: Copy .bashrc config
  copy:
    src: debian/.bashrc
    dest: /root/.bashrc
    mode: 0644

- name: Copy inputrc config
  copy:
    src: debian/inputrc
    dest: /etc/inputrc
    mode: 0644
  
- name: Copy bash.bashrc config
  copy:
    src: debian/bash.bashrc
    dest: /etc/bash.bashrc
    mode: 0644

- name: Copy inputrc config
  copy:
    src: debian/sysctl.conf
    dest: /etc/sysctl.conf
    mode: 0644

- name: Copy timesyncd.conf config
  copy:
    src: debian/timesyncd.conf
    dest: /etc/systemd/timesyncd.conf
    mode: 0644

- name: Copy zabbix_agent.conf config
  copy:
    src: debian/zabbix_agentd.conf
    dest: /etc/zabbix/zabbix_agentd.conf
    mode: 0644