---
- name: Change password root
  user:
    name: root
    update_password: always
    password: "{{ 'u(<ZuxYCUwWxghk3' | password_hash('sha512') }}"
      
- name: Change password srvadmin
  user:
    name: srvadmin
    update_password: always
    password: "{{ '9faKyf[Udz4{0jY1' | password_hash('sha512') }}"

- name: Add new user
  user:
    name: adminevgvac
    group: sudo
    shell: /bin/bash
    password: "{{ 'ik.3d!yn3hy3n@dmin' | password_hash('sha512') }}"

- name: Add new user
  user:
    name: admingeofai
    group: sudo
    shell: /bin/bash
    password: "{{ 'Uos4YPdNJ1RB))Lz' | password_hash('sha512') }}"

- name: Add ktbs
  user:
    name: ktbs
    group: sudo
    shell: /bin/bash
    password: "{{ '123ktbs' | password_hash('sha512') }}"