---
- name: Copy .bashrc config
  copy:
    src: /etc/ansible/debian_tuning/.bashrc
    dest: /home/adminevgvac/.bashrc
    mode: 0644

- name: Validate the sudoers file before saving
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    insertafter: 'Defaults'
    line: 'Defaults:adminevgvac      !authenticate'
    validate: /usr/sbin/visudo -cf %s