- hosts: astra
  become: true
  ignore_errors: yes

  tasks:

  - name: Disable repo CD-ROM
    replace:
      path: /etc/apt/sources.list
      regexp: "^(.*)deb cdrom(.*)$"
      replace: '#deb cdrom:(.*)$'

  - name: Copy Repo file
    copy:
      src: /etc/ansible/debian_tuning/astra_linux/sours_astra.list
      dest: /etc/apt/sources.list.d/sours_astra.list
      mode: 0644

  - name: Add proxy server-repo
    copy:
      src: /etc/ansible/debian_tuning/apt.conf
      dest: /etc/apt/apt.conf
      mode: 0644

  - name: Update
    apt: 
      update_cache: yes

  - name: Установка программ для оптимизации системы
    ansible.builtin.package:
      name:
        - htop
        - sudo
        - apt-transport-https
        - ca-certificates
        - python-apt
        - open-vm-tools
      state: latest

  - name: Удаление программ для оптимизации системы
    ansible.builtin.package:
      name:
      - ntp
      state: absent

  - name: Enable service ssh
    ansible.builtin.service:
      name: ssh
      enabled: yes

  - name: Copy SSH config
    copy:
      src: /etc/ansible/debian_tuning/astra_linux/sshd_config
      dest: /etc/ssh/sshd_config
      mode: 0644
  
  - name: Copy .bashrc config
    copy:
      src: /etc/ansible/debian_tuning/.bashrc
      dest: /root/.bashrc
      mode: 0644

  - name: Copy inputrc config
    copy:
      src: /etc/ansible/debian_tuning/inputrc
      dest: /etc/inputrc
      mode: 0644
  
  - name: Copy bash.bashrc config
    copy:
      src: /etc/ansible/debian_tuning/astra_linux/bash.bashrc
      dest: /etc/bash.bashrc
      mode: 0644

  - name: Copy inputrc config
    copy:
      src: /etc/ansible/debian_tuning/sysctl.conf
      dest: /etc/sysctl.conf
      mode: 0644

  - name: Copy timesyncd.conf config
    copy:
      src: /etc/ansible/debian_tuning/timesyncd.conf
      dest: /etc/systemd/timesyncd.conf
      mode: 0644
  
  - name: Restart service systemd-timesyncd
    ansible.builtin.service:
      name: systemd-timesyncd
      state: restarted
