# file: postgresql/tasks/extensions/contrib.yml

- name: PostgreSQL | Extensions | Make sure the postgres contrib extensions are installed | Debian OS system
  apt:
    name: "postgresql-contrib-{{ postgresql_version }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time | default (3600) }}"
  when: ansible_os_family in ['Debian', 'Astra Linux (Orel)', 'Astra Linux']
  notify:
    - restart postgresql
