- name: Backup BGP tables
  hosts: cisco
  gather_facts: false
  ignore_errors: yes

  tasks:

    - name: Accespt ansible net hostname
      ios_facts:
        gather_subset: all
      vars:
        ansible_command_timeout: 60

    - name: Get current date
      local_action: command date +%d-%b-%Y
      register: date

    - name: Get current time
      local_action: command date +%H-%M
      register: time

    - name: Create filder
      ios_config:
        backup: yes
        backup_options:
          filename: "{{ ansible_net_hostname }}_{{ ansible_host }}_{{ time.stdout }}_ip_bgp"
          dir_path: /etc/ansible/result/{{ date.stdout }}/{{ ansible_net_hostname }}

    - name: Get BGP teble
      ios_command:
        commands: show ip bgp
      register: ios_ip_bgp

    - name: copy ip_bgp to result folder
      copy:
        content: "{{ ios_ip_bgp.stdout[0] }}"
        dest: "/etc/ansible/result/{{ date.stdout }}/{{ ansible_net_hostname }}/{{ ansible_net_hostname }}_{{ ansible_host }}_{{ time.stdout }}_ip_bgp"
