- name: Backup Cisco Router or Switch
  hosts: cisco
  gather_facts: false

  tasks:

    - name: Accespt ansible net hostname
      ios_facts:
        gather_subset: all
      vars:
        ansible_command_timeout: 90

    - name: Get current date
      local_action: command date +%d-%b-%Y
      register: date

    - name: Copy flash:vlan.dat
      ansible.netcommon.cli_command:
        command: "copy flash:vlan.dat scp://srvadmin@10.33.64.228//etc/ansible/backups/vlan.dat"
        check_all: True
        prompt:
          - 'Source filename'
          - 'Address or name of remote host'
          - 'Destination filename'
        answer:
          - "\r"
          - "\r"
          - "test"
    
    - name: ansible copy file locally.
      copy:
        src: /etc/ansible/backups/vlan.dat
        dest: /etc/ansible/backups/{{ date.stdout }}/{{ ansible_net_hostname }}/{{ ansible_net_hostname }}_vlan.dat
      delegate_to: localhost
