- name: Enable logging
  hosts: cisco
  gather_facts: false
#  ignore_errors: yes
  
  tasks:

#    - name: Accept ansible get hostname
#      ios_facts:
#        gather_subset: all
#      vars:
#        ansible_command_timeout: 60

    - name: Enable Cisco logging to ELKStack
      cisco.ios.ios_config:
        lines:
          - logging trap debugging
          - logging origin-id hostname
          - logging host 10.33.64.231 transport udp port 5514
        replace: block
        backup: yes
        provider: "{{ cli }}"
      register: cfg

    - name: Show config updates
      debug: var=cfg.updates
      when: cfg.changed

    - name: Save config
      ios_command:
        commands:
          - write
        provider: "{{ cli }}"
      when: cfg.changed

    - name: show ntp
      ios_command:
        commands:
                - show run | incl logging
        provider: "{{ cli }}"
      register: out

    - name: Debug registered var
      debug: var=out.stdout_lines