- name: Enable logging
  hosts: cisco
  gather_facts: false
  
  tasks:

    - name: Ansible command timeout
      ios_facts:
        gather_subset: all
      vars:
        ansible_command_timeout: 120

    - name: Enable Cisco logging to ELKStack
      cisco.ios.ios_config:
        lines:
          - logging trap debugging
          - logging origin-id hostname
          - logging host 10.33.64.231 transport udp port 5514
        replace: block
        backup: yes
      register: cfg

    - name: Show config updates
      debug: var=cfg.updates
      when: cfg.changed

    - name: Save config
      ios_command:
        commands:
          - write
      when: cfg.changed

    - name: show run logging
      ios_command:
        commands:
                - show run | incl logging
      register: out

    - name: Debug registered var
      debug: var=out.stdout_lines