- name: Port-security
  hosts: cisco
  gather_facts: false
  ansible_become_method: false
#  ansible_become: false

  tasks:

    - name: Command clear port security
      cisco.ios.ios_command:
        commands: "clear port-security all"
