- name: Port-security
  hosts: cisco
  connection: network_cli

  tasks:

    - name: Command clear port security
      ios_command:
        commands: "clear port-security all"
        username: portsec
#        password: cisco
#        ssh_keyfile: /var/www/.ssh/id_rsa
