- name: Port-security
  hosts: cisco
  gather_facts: false
  remote_user: portsec

  tasks:

    - name: Command clear port security
      cisco.ios.ios_command:
        commands: "clear port-security all"
