- name: Port-security
  hosts: cisco
  gather_facts: false
#  connection: network_cli

  tasks:

    - name: Command clear port security
      ios_command:
        commands: 
          - "clear port-security all"
#        username: portsec
#        ssh_keyfile: /var/www/.ssh/id_rsa
#        register: ios_out

#    - debug: msg="{{ ios_out.stdout }}"
