- name: Copy ip dhcp snooping
  hosts: cisco
  gather_facts: false
  ignore_errors: yes

  tasks:

    - name: Accespt ansible net hostname
      ios_facts:
        gather_subset: all
      vars:
        ansible_command_timeout: 60

    - name: Get current date
      local_action: command date +%d-%b-%Y
      register: date

    - name: Create filder
      ios_config:
        backup: yes
        backup_options:
          filename: "{{ ansible_net_hostname }}_{{ ansible_host }}_ip_dhcp"
          dir_path: /etc/ansible/telefon/{{ date.stdout }}/{{ ansible_net_hostname }}

    - name: Get BGP teble
      ios_command:
        commands: show ip dhcp snooping binding
      register: ios_ip_dhcp

    - name: copy ip dhcp snooping to result folder
      copy:
        content: "{{ ios_ip_dhcp.stdout[0] }}"
        dest: "/etc/ansible/result/{{ date.stdout }}/{{ ansible_net_hostname }}/{{ ansible_net_hostname }}_{{ ansible_host }}_ip_dhcp"
