- name: Backup ARP VRF tables
  hosts: cisco
  gather_facts: false
  ignore_errors: yes

  tasks:

    - name: Accespt ansible net hostname
      ios_facts:
        gather_subset: all
      vars:
        ansible_command_timeout: 60

    - name: Get current date
      local_action: command date +%d-%b-%Y
      register: date

    - name: Get current time
      local_action: command date +%H-%M
      register: time

    - name: Create folder
      ios_config:
        backup: yes
        backup_options:
          filename: "{{ ansible_net_hostname }}_{{ ansible_host }}_{{ time.stdout }}ios_ip_arp_vrf_ao_kt"
          dir_path: /etc/ansible/result/{{ date.stdout }}/{{ ansible_net_hostname }}

    - name: Get arp vrf ao-kt teble
      ios_command:
        commands: show ip arp vrf ao-kt
      register: ios_ip_arp_vrf_ao_kt

    - name: copy ip_arp_vrf_ao_kt to result folder
      copy:
        content: "{{ ios_ip_arp_vrf_ao_kt.stdout[0] }}"
        dest: "/etc/ansible/result/{{ date.stdout }}/{{ ansible_net_hostname }}/{{ ansible_net_hostname }}_{{ ansible_host }}_{{ time.stdout }}_ip_arp_vrf_ao_kt"

    - name: Get arp vrf asutp teble
      ios_command:
        commands: show ip arp vrf asutp
      register: ios_ip_arp_vrf_asutp

    - name: copy ip_arp_vrf_asutp to result folder
      copy:
        content: "{{ ios_ip_arp_vrf_asutp.stdout[0] }}"
        dest: "/etc/ansible/result/{{ date.stdout }}/{{ ansible_net_hostname }}/{{ ansible_net_hostname }}_{{ ansible_host }}_{{ time.stdout }}_ip_arp_vrf_asutp"

    - name: Get vrf kt-cpu teble
      ios_command:
        commands: show ip arp vrf kt-cpu
      register: ios_ip_arp_vrf_kt_cpu

    - name: copy ip_arp_vrf_kt_cpu to result folder
      copy:
        content: "{{ ios_ip_arp_vrf_kt_cpu.stdout[0] }}"
        dest: "/etc/ansible/result/{{ date.stdout }}/{{ ansible_net_hostname }}/{{ ansible_net_hostname }}_{{ ansible_host }}_{{ time.stdout }}_ip_arp_vrf_kt_cpu"
