- name: Backup Cisco Router
  hosts: ciscoasa
  gather_facts: false
  ignore_errors: yes

  tasks:

#    - name: Accespt ansible net hostname
#      ios_facts:
#        gather_subset: all
#      vars:
#        ansible_command_timeout: 60

    - name: Get current date
      local_action: command date +%d-%b-%Y
      register: date

    - name: ASA CONFIG
      asa_command:
        commands: show running-config
      register: output

    - name: Get running-config and save it
      copy:
        content: "{{ output.stdout[0] }}"
        dest: /etc/ansible/backups/{{ date.stdout }}/{{ MSKCOD-ASA-5525X }}

#    - name: Get running-config and save it
#      ios_config:
#        backup: yes
#        backup_options:
#          filename: "{{ ansible_net_hostname }}_{{ ansible_host }}_running-config"
#          dir_path: /etc/ansible/backups/{{ date.stdout }}/{{ ansible_net_hostname }}

#    - name: Get running-config show
#      ios_command:
#        commands: show running-config view full
#      register: ios_run_cmd

    - name: copy startup-config to backup folder
      copy:
        content: "{{ output.stdout[0] }}"
        dest: "/etc/ansible/backups/{{ date.stdout }}/{{ MSKCOD-ASA-5525X }}/{{ MSKCOD-ASA-5525X }}_{{ MSKCOD-ASA-5525X }}_running-config"

#    - name: Get show startup-config
#      ios_command:
#        commands: show startup-config
#      register: ios_start_cmd

#    - name: copy startup-config to backup folder
#      copy:
#        content: "{{ ios_start_cmd.stdout[0] }}"
#        dest: "/etc/ansible/backups/{{ date.stdout }}/{{ ansible_net_hostname }}/{{ ansible_net_hostname }}_{{ ansible_host }}_startup-config"

