- name: Backup Cisco Router
  hosts: ciscoasa
  gather_facts: false
  ignore_errors: yes

  tasks:

    - name: Accespt ansible net hostname
      ios_facts:
        gather_subset: all
      vars:
        ansible_command_timeout: 60

    - name: Get current date
      local_action: command date +%d-%b-%Y
      register: date

    - name: Create folder for backup
      ios_config:
        backup: yes
        backup_options:
          filename: "{{ ansible_net_hostname }}_{{ ansible_host }}_running-config"
          dir_path: /etc/ansible/backups/{{ date.stdout }}/{{ ansible_net_hostname }}

    - name: Get startup-config
      asa_command:
        commands: show startup-config
      register: output

    - name: copy startup-config to backup folder
      copy:
        content: "{{ output.stdout[0] }}"
        dest: "/etc/ansible/backups/{{ date.stdout }}/{{ ansible_net_hostname }}/{{ ansible_net_hostname }}_{{ ansible_host }}_startup-config"
