---
# handlers file for roles/first_setup
- name: Restart service systemd-timesyncd
  service:
    name: systemd-timesyncd
    state: restarted

- name: Restart service SSH
  service:
    name: ssh
    state: restarted