ansible_user: netaud
ansible_ssh_pass: HI0EYzDW9IOeSQ8dFtqQ
ansible_connection: network_cli
ansible_network_os: ios
ansible_become: yes
ansible_become_method: enable
ansible_host_key_cheking: false
#ansible_ssh_extra_args='-o StrictHostKeyChecking=no'
#ansible_ssh_common_args='-o StrictHostKeyChecking=no'
