ansible_user: portsec
#ansible_ssh_pass: 
ansible_ssh_private_key_file: /var/www/.ssh/id_rsa
ansible_connection: network_cli
ansible_network_os: ios
ansible_become: yes
ansible_become_method: enable
ansible_host_key_cheking: false