- hosts: apache
  become: true

  tasks:

  - name: Update
    apt:
      update_cache: yes

  - name: Install Apache
    ansible.builtin.package:
      name:
        - apache2
      state: latest

  - name: Copy new config
    copy:
      src: /etc/ansible/debian_tuning/apache.conf
      dest: /etc/apache2/sites-available/
      mode: 0640

  - name: Deactivates the default virtualhost
    command: a2dissite 000-default.conf

  - name: Deactivates the default ssl virtualhost
    command: a2dissite default-ssl

  - name: Activates our virtualhost
    command: a2ensite apache.conf

  - name: Apache is restarted
    ansible.builtin.service:
      name: apache2
      state: restarted
