- hosts: linux
  become: true

  tasks:

  - name: insert line in file
    lineinfile: 
      dest=/etc/zabbix/zabbix_agentd.conf
      insertafter="^ListenPort=10050" 
      line="ListenIP={{ ansible_default_ipv4.address }}"
