- hosts: linux
  become: true

  tasks:

  - name: Change password root
    user:
      name: root
      update_password: always
      password: "{{ 'u(<ZuxYCUwWxghk3' | password_hash('sha512') }}"
      
  - name: Change password srvadmin
    user:
      name: srvadmin
      update_password: always
      password: "{{ '9faKyf[Udz4{0jY1' | password_hash('sha512') }}"
