- hosts: linux
  become: true

  tasks:

  - name: Add new user
    user:
      name: adminss1
      group: sudo
      shell: /bin/bash
      password: "{{ 'JfIlZt5Wy<)1E7y]' | password_hash('sha512') }}"

#  - name: Add new user
#    user:
#      name: adminartbyd
#      group: sudo
#      shell: /bin/bash
#      password: "{{ 'test' | password_hash('sha512') }}"
