- hosts: linux
  become: true

  tasks:

  - name: Add new user
    user:
      name: adminevgvac
      group: sudo
      shell: /bin/bash
      password: "{{ 'ik.3d!yn3hy3n@dmin' | password_hash('sha512') }}"

  - name: Copy .bashrc config
    copy:
      src: /etc/ansible/debian_tuning/.bashrc
      dest: /home/adminevgvac/.bashrc
      mode: 0644

  - name: Validate the sudoers file before saving
    ansible.builtin.lineinfile:
      path: /home/adminevgvac/sudoers
      state: present
      insertafter: 'Defaults'
      line: 'Defaults:adminevgvac      !authenticate'
      validate: /usr/sbin/visudo -cf %s

  - name: Add new user
    user:
      name: admingeofai
      group: sudo
      shell: /bin/bash
      password: "{{ 'Uos4YPdNJ1RB))Lz' | password_hash('sha512') }}"

  - name: Add new user
    user:
      name: adminss1
      group: sudo
      shell: /bin/bash
      password: "{{ 'ewme<OFV[99ndlIF' | password_hash('sha512') }}"