- hosts: linux
  become: true

  tasks:

  - name: Update
    apt: 
      update_cache: yes

  - name: Установка программ для оптимизации системы
    ansible.builtin.package:
      name:
        - haproxy
      state: latest
