- hosts: linux
  become: true

  tasks:

  - name: Validate the sudoers file before saving
    ansible.builtin.lineinfile:
      path: /home/adminevgvac/sudoers
      state: present
      regexp: ^secure_path=*
      line: '^ADMIN ALL=(ALL) NOPASSWD: ALL'
      validate: /usr/sbin/visudo -cf %s

  - name: Set hostname on conf file
    lineinfile:
      dest: /etc/zabbix/zabbix_agentd.conf
      regexp: ^Hostname=.*
      insertafter: ^# Hostname=
      line: Hostname=Server Linux {{ ansible_hostname }}