- hosts: linux
  become: true

  tasks:

  - name: Add new user
    user:
      name: adminevgvac
      group: sudo
      shell: /bin/bash
      password: "{{ 'test1234' | password_hash('sha512') }}"
      
  - name: Add new user
    user:
      name: admingeofai
      group: sudo
      shell: /bin/bash
      password: "{{ 'test1234' | password_hash('sha512') }}"

  - name: Creating user with admin access
    user: 
      name: tester
      shell: /bin/bash
      password: "{{ 'test1234' | password_hash('sha512') }}"
      groups: admin append=yes
    when:  assigned_role  == "yes"